name: Run All Tests

on:
  pull_request:
    branches:
      - 'master'
  push:
  workflow_dispatch:

jobs:
  tests:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install Dependencies
        run: npm ci

      - name: Run tests
        run: npm test
